server:
  port: 8082

spring:
  application:
    name: TaskService

  datasource:
    url: ${PG_URL}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jooq:
    sql-dialect: postgres

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      properties:
        enable:
          idempotence: true
      acks: all

  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_PROVIDER_URI}
        client-registration-name: task-service-client
        registration:
          task-service-client:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: ${spring.application.name}
            client-secret: ${TASK_CLIENT_SECRET}
            client-authentication-method: client_secret_basic
            scope: openid

kafka:
  topic-names:
    task-created: ${TASK_CREATED_TOPIC}