DROP TABLE IF EXISTS public.user CASCADE;

CREATE TABLE IF NOT EXISTS public.user
(
    id_user           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    role              VARCHAR(20)  NOT NULL DEFAULT 'ROLE_USER',
    avatar_link       VARCHAR(100),
    username          VARCHAR(50)  NOT NULL,
    name              VARCHAR(50),
    last_name         VARCHAR(50),
    password          VARCHAR(100) NOT NULL,
    email             VARCHAR(50)  NOT NULL UNIQUE,
    date_registration TIMESTAMP    NOT NULL DEFAULT current_timestamp,
    last_login        TIMESTAMP    NOT NULL DEFAULT current_timestamp,
    activity          BOOLEAN      NOT NULL DEFAULT FALSE::BOOLEAN
);