DROP TABLE IF EXISTS
    public.user,
    user_background,
    auth,
    confirmation_code,
    user_idempotency_key
    CASCADE;

CREATE TABLE IF NOT EXISTS public.user
(
    id_user     BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    role        VARCHAR(20) NOT NULL DEFAULT 'ROLE_USER',
    avatar_link VARCHAR(250),
    username    VARCHAR(50) NOT NULL UNIQUE,
    name        VARCHAR(50),
    last_name   VARCHAR(50),
    email       VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS user_background
(
    id_background     BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_registration TIMESTAMP   NOT NULL DEFAULT current_timestamp,
    last_login        TIMESTAMP,
    timezone          VARCHAR(50) NOT NULL,
    activity          BOOLEAN     NOT NULL DEFAULT FALSE::BOOLEAN,
    id_user           BIGINT UNIQUE REFERENCES public.user (id_user) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS auth
(
    id_auth          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_user          BIGINT    NOT NULL REFERENCES public.user (id_user) ON DELETE CASCADE,
    auth_type        VARCHAR(20),
    auth_provider_id VARCHAR(100),
    password         VARCHAR(100),
    created_at       TIMESTAMP NOT NULL DEFAULT current_timestamp,

    UNIQUE (auth_type, auth_provider_id),
    UNIQUE (id_user, auth_type)
);

CREATE TABLE IF NOT EXISTS confirmation_code
(
    id_code      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_user      BIGINT    NOT NULL,
    code         INTEGER   NOT NULL,
    created_date TIMESTAMP NOT NULL DEFAULT current_timestamp,
    UNIQUE (id_user, code)
);

CREATE TABLE IF NOT EXISTS user_idempotency_key
(
    id_key UUID PRIMARY KEY,
    created_at DATE NOT NULL DEFAULT current_date
);