DROP TABLE IF EXISTS public.user, auth CASCADE;

CREATE TABLE IF NOT EXISTS public.user
(
    id_user           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    role              VARCHAR(20) NOT NULL DEFAULT 'ROLE_USER',
    avatar_link       VARCHAR(250),
    username          VARCHAR(50) NOT NULL UNIQUE,
    name              VARCHAR(50),
    last_name         VARCHAR(50),
    email             VARCHAR(50) NOT NULL UNIQUE,
    date_registration TIMESTAMP   NOT NULL DEFAULT current_timestamp,
    last_login        TIMESTAMP,
    activity          BOOLEAN     NOT NULL DEFAULT FALSE::BOOLEAN
);

CREATE TABLE IF NOT EXISTS auth
(
    id_auth          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_user          BIGINT      NOT NULL REFERENCES public.user (id_user) ON DELETE CASCADE,
    auth_type        VARCHAR(20) NOT NULL,
    auth_provider_id VARCHAR(100),
    password         VARCHAR(100),
    created_at       TIMESTAMP   NOT NULL DEFAULT current_timestamp,

    UNIQUE (auth_type, auth_provider_id),
    UNIQUE (id_user, auth_type)
)