server:
  port: 8082

spring:
  application:
    name: ProgressService

  datasource:
    url: ${PG_URL}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: ${spring.application.name}
      properties:
        spring:
          json:
            trusted:
              packages: com.javalab.core.events
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
      client:
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_PROVIDER_URI}
        client-registration-name: progress-service-client
        registration:
          progress-service-client:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: ${spring.application.name}
            client-secret: ${PROGRESS_CLIENT_SECRET}
            client-authentication-method: client_secret_basic
            scope: openid

kafka:
  topic-names:
    user-registered: ${USER_REGISTERED_TOPIC:user-registered-topic}
    user-logged-in: ${USER_LOGGED_IN_TOPIC:user-logged-in-topic}
    execution-attempt: ${EXECUTION_ATTEMPT_TOPIC:execution-attempt-topic}

logging:
  level:
    org.springframework: INFO
    com.wenn.progressservice: DEBUG