server:
  port: 8080

spring:
  application:
    name: UserService
    scheduler:
      zone: Europe/Moscow
      delete-user:
        cron: "* * 6 * * *"
        key-lifetime: 1d
  task:
    scheduling:
      pool:
        size: 2

  datasource:
    url: ${PG_URL}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none

  redis:
    user-lock:
      queue-key: delayed:user:locks
      processed-prefix: "lock:processed:"
      dlq-key: lock:dead-letter
      processed-ttl: 24h

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      properties:
        enable:
          idempotence: true
      acks: all

    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: com.javalab.core.events
        spring.json.use.type.headers: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}

keycloak:
  admin:
    url: ${KEYCLOAK_URL}
    realm: ${KEYCLOAK_REALM}
    current-realm: ${KEYCLOAK_CURRENT_REALM}
    username: ${KEYCLOAK_USERNAME}
    password: ${KEYCLOAK_PASSWORD}
    client-id: admin-cli

auth:
  confirmation-code:
    lifetime: 15m

s3:
  minio:
    endpoint: ${MINIO_ENDPOINT}
    region: ${MINIO_REGION}
    bucket-name: java-lab
    access-key: ${MINIO_ACCESS_KEY}
    application-key: ${MINIO_APP_KEY}
    path-style: true
  avatar-prefix: user-avatars

kafka:
  topic-names:
    user-registered: ${USER_CREATED_TOPIC}
    user-logged-in: ${USER_LOGGED_IN_TOPIC}
    oauth2-user-logged-in: ${OAUTH2_LOGIN_TOPIC}
    user-locked: ${USER_LOCKED_TOPIC}