server:
  port: 8083

spring:
  application:
    name: NotificationService

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: ${KAFKA_CONSUMER_GROUP}
      properties:
        spring:
          json:
            trusted:
              packages: com.yuranium.javalabcore
    properties:
      telemetry.enabled: false


  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_PROVIDER_URI}
        client-registration-name: notification-service-client
        registration:
          notification-service-client:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: ${spring.application.name}
            client-secret: ${NOTIFICATION_CLIENT_SECRET}
            client-authentication-method: client_secret_basic
            scope: openid

kafka:
  topic-names:
    user-registered: ${KAFKA_TOPIC_USER_REGISTERED}
    task-created: ${KAFKA_TOPIC_TASK_CREATED}

services:
  user-service:
    url: ${USER_SERVICE_HOST}