DROP TABLE IF EXISTS
    public.user,
    user_background,
    confirmation_code
    CASCADE;

CREATE TABLE IF NOT EXISTS public.user
(
    id_user     BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    keycloak_id UUID        NOT NULL UNIQUE,
    avatar_link VARCHAR(250),
    username    VARCHAR(50) NOT NULL UNIQUE,
    name        VARCHAR(50),
    last_name   VARCHAR(50),
    email       VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS user_background
(
    id_background     BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_registration TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_login        TIMESTAMPTZ,
    timezone          VARCHAR(50) NOT NULL,
    notify_enabled    BOOLEAN     NOT NULL DEFAULT TRUE,
    activity          BOOLEAN     NOT NULL DEFAULT FALSE::BOOLEAN,
    id_user           BIGINT UNIQUE REFERENCES public.user (id_user) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS confirmation_code
(
    id_code      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_user      BIGINT      NOT NULL,
    code         INTEGER     NOT NULL,
    created_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (id_user, code)
);