services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    restart: "no"
    ports:
      - "${PG_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-postgres}
      POSTGRES_DB: postgres
volumes:
  postgres_data: